# Generated by Django 4.2 on 2023-05-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('documento', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.TextField(max_length=20)),
                ('direccion', models.TextField(max_length=20)),
                ('genero', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lineas_de_credito',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre_credito', models.TextField(max_length=20)),
                ('monto_maximo', models.PositiveBigIntegerField(verbose_name='Monto maximo')),
                ('plazo_maximo', models.PositiveSmallIntegerField(verbose_name='Plazo maximo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=10)),
                ('nombre_usu', models.TextField(max_length=50)),
                ('clave', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_prestado', models.PositiveBigIntegerField(verbose_name='Prestado')),
                ('plazo', models.PositiveSmallIntegerField(choices=[('m', 6), ('m', 12), ('m', 18), ('m', 24)], default=6, verbose_name='Plazo maximo')),
                ('fecha_desembolso', models.DateField()),
                ('cod_lineacredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBanco.lineas_de_credito')),
                ('documento_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBanco.cliente')),
            ],
        ),
    ]
