# Generated by Django 4.2 on 2023-05-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBanco', '0002_delete_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_prestado', models.PositiveBigIntegerField(verbose_name='Prestado')),
                ('plazo', models.PositiveSmallIntegerField(choices=[('m', 6), ('m', 12), ('m', 18), ('m', 24)], default=6, verbose_name='Plazo maximo')),
                ('fecha_desembolso', models.DateField()),
                ('cod_lineacredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBanco.lineas_de_credito')),
                ('documento_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBanco.cliente')),
            ],
        ),
    ]
