# Generated by Django 4.2 on 2023-05-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBanco', '0003_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditos',
            name='fecha_desembolso',
        ),
    ]
