# Generated by Django 4.2 on 2023-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBanco', '0004_remove_creditos_fecha_desembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='plazo',
            field=models.PositiveSmallIntegerField(choices=[(6, 6), (12, 12), (18, 18), (24, 24)], default=6, verbose_name='Plazo maximo'),
        ),
    ]
